connections:
  sqlite:
    driver: "sqlite3"
    dsn: "./db.sqlite"
  mysql:
    driver: "mysql"
    dsn: "${DB_USERNAME}:${DB_PASSWORD}@tcp(${DB_HOST}:${DB_PORT})/${DB_DATABASE}?charset=utf8&parseTime=true"
  ecom:
    driver: "mysql"
    dsn: "${DB_USERNAME}:${DB_PASSWORD}@tcp(${DB_HOST}:${DB_PORT})/ecom?charset=utf8&parseTime=true"
